org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=euclidia
display_name=Euclidia
license=MIT
group_id=net.forixaim
authors=Forixaim
issue_tracker=https://github.com/Forixaim/Mana-Arts/issues
source_code=https://github.com/Forixaim/Mana-Arts
display_url=https://github.com/Forixaim/Mana-Arts
credits="Me"
description=Euclidia implements a pathfinding path smoothing onto Mob pathing this leads to higher CPU demands but a reduced number of nodes.
